# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Test on all platforms

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    name: ğŸ§ª Cross-platform tests
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        runner: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: ğŸ§© Checkout repository
        uses: actions/checkout@v4

      - name: âš™ï¸ Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: ğŸ§± Restore and Build
        run: dotnet build DrumBuddy.Desktop -c Release /p:VSTestLogger=

        
      - name: ğŸ§ª Run tests
        run: dotnet test DrumBuddy.Unit/DrumBuddy.Core.Unit.csproj --configuration Release --no-build --verbosity normal --logger "console;verbosity=detailed"
        env:
          DOTNET_ROLL_FORWARD: Major


